### ISSUE TITLE
重启docker服务后所有用户强制退出

### ISSUE THREAD

**Issue by FireOra** [TangSengDaoDao/TangSengDaoDaoServer#105]
我这边服务器配置好tsdd的.env的ip，但服务器ip偶然会变化，然后我把.env的ip改对后用docker stop 和 up -d重启服务，但这样会导致所有用户都强制退出，用户需重新输入账密登陆app。

有无办法ip变了后改好后，重启服务用户不会强制退出？

**Comment by tangtaoit** [comment]
不要重启redis，因为redis是内存数据库，重启后登录token就失效了，导致退出

**Comment by FireOra** [comment]
原来如此，问题已解决，感谢作者解答
