### ISSUE TITLE
WKMsg等相关实体未实现 Serializable 接口导致无法在页面中传递

### ISSUE THREAD

**Issue by wyy-dev** [TangSengDaoDao/TangSengDaoDaoServer#110]
# 现象
WKSDK Android WKMsg等相关实体未实现 Serializable 接口导致无法在页面中传递
# 日志

**Comment by No8blackball** [comment]
`WKMsg`是实现的`Parcelable`。页面之间也可以通过`clientMsgNo`字段进行传递和查询消息

**Comment by wyy-dev** [comment]
你好，我这里页面之间必须要使用 Serializable 序列化，能麻烦适配一下吗

**Comment by No8blackball** [comment]
> 你好，我这里页面之间必须要使用 Serializable 序列化，能麻烦适配一下吗

可以传递`clientMsgNo`，在新页面通过`WKIM.getInstance().getMsgManager().getWithClientMsgNO()`方法查询
