### ISSUE TITLE
消息撤回失败问题！

### ISSUE THREAD

**Issue by iBeiTa** [TangSengDaoDao/TangSengDaoDaoServer#112]
# 现象
webhook链接正常 发送消息的数据没存到message 
# 日志
发送消息提示这个
![WechatIMG130](https://github.com/user-attachments/assets/1dce19f4-33af-4eb2-be4d-674a0a256eb3)

**Comment by tangtaoit** [comment]
那种方式部署的？ WuKongIM用的那个版本？

**Comment by iBeiTa** [comment]
> WuKongIM 用的那个版本？
最新版本 
wukongim/wukongim:latest

**Comment by iBeiTa** [comment]
> 那种方式部署的？ WuKongIM用的那个版本？

知道了 谢谢作者 解决了 要WuKong 1.2版本 🐮
