### ISSUE TITLE
集群部署，A和B对话，  A用户连接 节点1服务器对话， B用户连接节点2服务器对话， 两个对话怎么互通的

### ISSUE THREAD

**Issue by akidongzi** [TangSengDaoDao/TangSengDaoDaoServer#119]
集群部署，A和B对话，  A用户连接 节点1服务器对话， B用户连接节点2服务器对话， 两个对话怎么互通的，麻烦回复下

**Comment by tangtaoit** [comment]
这个问题应该在WuKongIM提。

通过用户的uid的hash计算出所在slot，slot所在节点就是用户的节点，获得对应的节点然后转发给对方。
