### ISSUE TITLE
重启后获取地址变成内网ip了

### ISSUE THREAD

**Issue by nie-e** [TangSengDaoDao/TangSengDaoDaoServer#12]
# 现象
<img width="966" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/63990855/40000a33-c22a-4c83-8806-aaf6d6cf8812">
docker 获取的都是ws都是内网端口，外网端口都已经打开了，可以登录但是连接不上
开始启动成功了，但是后面重启了一下就成这个样子了

# 日志

**Comment by tangtaoit** [comment]
参考：https://github.com/TangSengDaoDao/TangSengDaoDaoServer/issues/9

**Comment by nie-e** [comment]
<img width="714" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/63990855/1722d783-65b2-4e90-898f-3a1e6759705f">
尝试添加了docker-compose.yaml文件中，就ok了。添加在wk文件中，有时候会获取不对。
