### ISSUE TITLE
docker容器启动，系统centos7，miniO启动不了

### ISSUE THREAD

**Issue by a535702237** [TangSengDaoDao/TangSengDaoDaoServer#14]
# 现象
miniO启动不了，tsdd.yaml也配置了，9000端口没启动
# 日志
ERROR Invalid MINIO_BROWSER_REDIRECT_URL value in environment variable: unexpected scheme found 
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/21998288/36bf8a18-51d2-40a1-81ab-6c5520b926d5)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/21998288/6cffdced-035c-4cad-b5c2-99e11557196c)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/21998288/720807fc-0745-4589-9120-724250243a89)

**Comment by tangtaoit** [comment]
MINIO_BROWSER_REDIRECT_URL: ""  # 这里填空
