### ISSUE TITLE
提议：主要贡献者使用GPG签名提交

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [TangSengDaoDao/TangSengDaoDaoServer#19]
如题，GPG签名提交能有效防止供应链攻击，防止冒充，而紧箍咒Server目标是企业内部IM，冒充是有利可图的。

如果可以的话，记得上传公钥到密钥服务器，并在readme里注明主要贡献者的密钥指纹。

**Comment by tangtaoit** [comment]
好建议，后续可以考虑
