### ISSUE TITLE
调试启动时报链接失败，请问是什么配置没配么？

### ISSUE THREAD

**Issue by AKIRAGuo** [TangSengDaoDao/TangSengDaoDaoServer#20]
# 现象
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7629219/9ac20d7f-bdd0-4de2-a833-e34fed1a5f6e)

![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7629219/513800fd-460c-4e9f-8f59-71f5a72b1a27)
这里端口冲突我给改了如果是这里的原因麻烦问下要改哪配置文件要改么？
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7629219/1d3eea4f-11b6-41a5-bf04-d9b41305d1ed)

# 日志

**Comment by AKIRAGuo** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7629219/b0c9f90b-ee91-4af2-9c48-f5f271d7fbbc)
配置wen文件中修改了端口号目前报这个
![1691543781928](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7629219/5bb539bc-a8a5-45cb-bc0c-71e46b5a2c32)

**Comment by tangtaoit** [comment]
yaml的docker部分，- 3307:3307 改成 - 3307:3306
