### ISSUE TITLE
希望添加卡片消息支持

### ISSUE THREAD

**Issue by liesauer** [TangSengDaoDao/TangSengDaoDaoServer#22]
通过阅读文档，自定义消息需要自己实现，包括各端的显示渲染，这成本太大了，得会三端的开发语言。能不能官方出一个类似于微信的那种卡片消息，发送信息只需要发送对应的模板信息，其他链接、标题、图片、按钮等内容就按照设定好的卡片消息渲染。

**Comment by tangtaoit** [comment]
记录了，后续安排开发
