### ISSUE TITLE
关于音视频，性能等问题

### ISSUE THREAD

**Issue by Cloud-Yao** [TangSengDaoDao/TangSengDaoDaoServer#26]
# 文档
 希望官方能够有像腾讯云IM服务那种不同客户端SDK文档，例如“含UI集成方案”和”不含UI集成方案“的客户端SDK文档；
# Flutter
 官方有计划推出Flutter的SDK吗？如果有，大概什么时间可以出炉呢？
# 音视频
 现在官方有计划推出类似像腾讯会议类似的服务，最好可以直接集成在群聊中
# 服务
 IM服务的性能如何？支持集群部署吗？如何保证高可用？IM消息存储？群聊最多支持多人加入？人多之后会有哪些比较大的影响，希望能在官方文档中有一个详细的说明

**Comment by tangtaoit** [comment]
> 希望官方能够有像腾讯云IM服务那种不同客户端SDK文档，例如“含UI集成方案”和”不含UI集成方案“的客户端SDK文档；

SDK文档就是悟空IM的文档  https://githubim.com  UI集成方案看唐僧叨叨的文档  https://tangsengdaodao.com

> 官方有计划推出Flutter的SDK吗？如果有，大概什么时间可以出炉呢？

Flutter SDK在开发中

> 现在官方有计划推出类似像腾讯会议类似的服务，最好可以直接集成在群聊中

腾讯会议类似的没有，只有微信类似的群聊视频（属于收费模块）

>IM服务的性能如何？支持集群部署吗？如何保证高可用？IM消息存储？群聊最多支持多人加入？人多之后会有哪些比较大的影响，希望能在官方文档中有一个详细的说明

这个在悟空IM已经回答你了 https://github.com/WuKongIM/WuKongIM/issues/22
