### ISSUE TITLE
短信验证问题

### ISSUE THREAD

**Issue by zhanshengxiaoyu** [TangSengDaoDao/TangSengDaoDaoServer#28]
# 现象
更换成阿里云短信后把 tsdd.yaml配置的smsCode值留空 屏蔽都不管用
手机收到阿里云发的验证码 验证还是走smsCode配置的值

是不是除了 tsdd.yaml配置还有别的地方需要关掉
# 日志

**Comment by tangtaoit** [comment]
除了 tsdd.yaml 的smsCode的配置 没有其他需要改的地方
