### ISSUE TITLE
(TangSengDaoDaoWeb)windows版本build后无法正常访问自行部署的HTTP后台

### ISSUE THREAD

**Issue by yinlulu0127** [TangSengDaoDao/TangSengDaoDaoServer#33]
修改index.tsx
if(process.env.NODE_ENV === "development") {
  WKApp.apiClient.config.apiURL = "http://10.113.3.77:8090/v1/"
}else {
  // WKApp.apiClient
  WKApp.apiClient.config.apiURL = "http://10.113.3.77:8090/v1/";
}

# 现象
1. yarn dev 网页访问后台正常
2. yarn build后 liveserver启动网页访问后台正常
3. yarn tauri dev windows程序访问后台正常
4. yarn tauri build，安装后程序访问后台异常
5. 修改为官方https api，WKApp.apiClient.config.apiURL = "https://api.botgate.cn/v1/"修改后 重新 yarn tauri build，安装后程序访问官方后台正常
# 日志
axios.interceptors.response.use 中报错 Nerwork Error

**Comment by tangtaoit** [comment]
需要使用https
