### ISSUE TITLE
mac 客户端可以连接自己 搭建的im服务么

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoServer#35]
# 现象
mac 客户端是免费的么，可以连接自己 搭建的im服？怎么去配置自己的服务IP呢

**Comment by tangtaoit** [comment]
是免费的，通过修改源码的的服务器地址，然后重新打包，https://github.com/TangSengDaoDao/TangSengDaoDaoWeb

**Comment by echo-music** [comment]
> 是免费的，通过修改源码的的服务器地址，然后重新打包，https://github.com/TangSengDaoDao/TangSengDaoDaoWeb

多谢你
