### ISSUE TITLE
第三方应用可调用api自动注册用户信息，静默添加好友，创建群聊么？

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoServer#36]
您好，咱们支持在第三方应用可调用im接口批量注册用户到im，并互加好友，创建群聊么？

**Comment by tangtaoit** [comment]
批量注册的接口暂没有

**Comment by echo-music** [comment]
谢谢你，

1、添加好友必须用户登陆后才能选择添加，不登陆可以直接通过第三方应用掉接口添加好友么？
2、创建群聊也必须用户登陆才能选择好友加入到群聊，不能通过第三方应用去操作创建群聊么
以上理解对么？

**Comment by tangtaoit** [comment]
对的，如果要实现上面2点，你需要自己稍作开发。
