### ISSUE TITLE
使用docker-compose 部署服务报错，数据库连接错误

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoServer#40]
# 现象
tsdd-tangsengdaodaoserver-1   | panic: dial tcp 192.168.224.8:3306: connect: connection refused

然后测试添加好友也不能加了

# 日志
register......
tsdd-wukongim-1               | [GIN] 2023/10/13 - 23:35:32 | 200 |     3.45653ms |  192.168.224.10 | POST     "/user/token"
tsdd-tangsengdaodaoserver-1   | panic: dial tcp 192.168.224.8:3306: connect: connection refused
tsdd-tangsengdaodaoserver-1   | 
tsdd-tangsengdaodaoserver-1   | goroutine 1 [running]:
tsdd-tangsengdaodaoserver-1   | main.runAPI(0xc0002ccc00)
tsdd-tangsengdaodaoserver-1   |         /go/release/main.go:95 +0x1d5
tsdd-tangsengdaodaoserver-1   | main.main()
tsdd-tangsengdaodaoserver-1   |         /go/release/main.go:70 +0x3ed
tsdd-mysql-1                  | 2023-10-13T15:35:32.587981Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
tsdd-mysql-1                  | 2023-10-13T15:35:32.588016Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.27) starting as process 1
tsdd-mysql-1                  | 2023-10-13T15:35:32.593107Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
tsdd-mysql-1                  | 2023-10-13T15:35:32.603044Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.

**Comment by tangtaoit** [comment]
检查数据库的连接地址是否正确
