### ISSUE TITLE
通过 gihub action打包 process.env.NODE_ENV 需要修改成production么？

### ISSUE THREAD

**Issue by echo-music** [TangSengDaoDao/TangSengDaoDaoServer#41]
# 现象
通过gihub action打包，下载该pc安装包进行登陆，发现请求的IP是旧的IP，于是看文档修改了export API_URL="https://10.30.0.23/v1/"
然后再次访问发现地址还是请求的是旧的地址。该怎么动态修改API_URL 呢？需要把  process.env.NODE_ENV 修改成production么？

![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/5945928/dec7eda4-223b-49ea-a913-709f2fe51865)
正确的地址应该是 10.30.0.23

**Comment by tangtaoit** [comment]
修改 https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/blob/main/apps/web/src/index.tsx#L11 的apiURL变量为你自己的api地址
