### ISSUE TITLE
建议PC客户端可以自行设置服务端的连接地址

### ISSUE THREAD

**Issue by xmlgrg** [TangSengDaoDao/TangSengDaoDaoServer#45]
# 现象
并不是所有的使用者都会 编译客户端
# 日志

**Comment by tangtaoit** [comment]
> 悲摧，，，linux我服务端都跑不起来

多看文档，实在搞不定可以加官网的微信，让他拉你进群

**Comment by ztcjn** [comment]
> > 悲摧，，，linux我服务端都跑不起来
> 
> 多看文档，实在搞不定可以加官网的微信，让他拉你进群

问题的关键是没有文档。。。。。

**Comment by tangtaoit** [comment]
https://tsdaodao.com/dev/backend/deploy-compose.html 这不是文档吗？ 部署文档一把梭，已经够简单了
