### ISSUE TITLE
docker-compose方式启动，数据库默认编码为latin1，导致server初始化数据库失败，无法启动

### ISSUE THREAD

**Issue by timeLikeSong** [TangSengDaoDao/TangSengDaoDaoServer#46]
# 现象
docker-compose方式启动，数据库默认编码为latin1，导致server初始化数据库失败，无法启动

# 日志

tangsengdaodaoserver_1   | register......
tangsengdaodaoserver_1   | panic: Error 1366 (HY000): Incorrect string value: '\xE5\x9F\xBA\xE7\xA1\x80...' for column 'name' at row 1 handling common-20230203-01.sql
tangsengdaodaoserver_1   | 
tangsengdaodaoserver_1   | goroutine 1 [running]:
tangsengdaodaoserver_1   | main.runAPI(0xc0002f2b00)
tangsengdaodaoserver_1   | 	/go/release/main.go:95 +0x1d5
tangsengdaodaoserver_1   | main.main()
tangsengdaodaoserver_1   | 	/go/release/main.go:70 +0x3ed
mysql_1                  | 2023-11-09T05:34:12.190718Z 2 [Note] Aborted connection 2 to db: 'im' user: 'root' host: '172.22.0.8' (Got an error reading communication packets)

tangsengdaodaoserver_1   | register......
tangsengdaodaoserver_1   | panic: Error 1050 (42S01): Table 'app_module' already exists handling common-20230203-01.sql
tangsengdaodaoserver_1   | 
tangsengdaodaoserver_1   | goroutine 1 [running]:
tangsengdaodaoserver_1   | main.runAPI(0xc0001e0a00)
tangsengdaodaoserver_1   | 	/go/release/main.go:95 +0x1d5
tangsengdaodaoserver_1   | main.main()
tangsengdaodaoserver_1   | 	/go/release/main.go:70 +0x3ed

# 解决方式

在启动数据库的时候增加默认编码参数
mysql:  # mysql数据库
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

**Comment by tangtaoit** [comment]
感谢
