### ISSUE TITLE
IOS端 能够正常收到信息推送,Android无法收到信息推送,只有进入APP后才能收到信息.

### ISSUE THREAD

**Issue by starkiller43** [TangSengDaoDao/TangSengDaoDaoServer#47]
# 现象
IOS端 能够正常收到信息推送,Android无法收到信息推送,只有进入APP后才能收到信息.已关闭电池优化,及给预了所有通知权限
测试了多台Android设备
# 日志

**Comment by tangtaoit** [comment]
需要在配置里配置手机厂商的appid和对应appkey 
![WX20231112-151754@2x](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/ec1ea24e-df14-4e57-9393-4d44fa8737cd)

https://tsdaodao.com/dev/backend/fullconfig.html

**Comment by zuoliang0** [comment]
请问可以自定义推送吗？或者支持GOOGLE的firebase？

**Comment by tangtaoit** [comment]
> 请问可以自定义推送吗？或者支持GOOGLE的firebase？

可以，参考其他推送的实现即可
