### ISSUE TITLE
浏览器未知错误

### ISSUE THREAD

**Issue by hhy520wmf** [TangSengDaoDao/TangSengDaoDaoServer#48]
# 现象

# 日志
![1700724803392](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/66a52ee9-903f-4295-9a9c-38db461e7af4)

![1700724843193](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/794db157-be53-4f24-b889-db892737a1b2)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/c3a5b2a8-403a-4548-a72d-4167c8dd6501)

**Comment by hhy520wmf** [comment]
![1700724947439](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/11ef891f-ba50-44ca-9b23-75b1240de92e)

**Comment by tangtaoit** [comment]
你基础地址填写对了吗，我看你直接填的IP没有填端口 如果没修改过端口的情况下 api的地址的端口是 8090

**Comment by hhy520wmf** [comment]
![1700725134801](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/14cf43a8-558c-46e1-aa14-d1ec9d0aa3d5)

**Comment by hhy520wmf** [comment]
直接填 ip还是 ip+8090的形式，我是直接填的ip

**Comment by tangtaoit** [comment]
http://ip:8090/v1/
