### ISSUE TITLE
Docker Compose 部署 启动失败，并没进程占用该端口，

### ISSUE THREAD

**Issue by hhy520wmf** [TangSengDaoDao/TangSengDaoDaoServer#49]
# 现象
原本有docker -pr的中的进程占用，我结束掉了，也无法启动，还是显示端口被占用
# 日志
![1700734339861](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/f9bfeef6-04b3-418a-b984-117a01c56f6f)
![1700734463178](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/777a5249-d048-46c5-9093-f669026e7cb7)

**Comment by tangtaoit** [comment]
你电脑上是否部署过WuKongIM？ 唐僧叨叨部署脚本里自带了WuKongIM。按照这个教程https://tsdaodao.com/dev/backend/deploy-compose.html  （最好是干净的机器安装）
