### ISSUE TITLE
daodaoserver下载源码后build时报git错误

### ISSUE THREAD

**Issue by qiuxunbiao** [TangSengDaoDao/TangSengDaoDaoServer#50]
# 现象
从github上下载源代码后执行build操作，然后报git错误——not a git repository (or any of the parent directories)：.
![微信图片_20231124093715](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/69827385/59e09c96-f3d9-4eea-92ff-f49e80b96b1e)
git。
# 日志

**Comment by tangtaoit** [comment]
通过git clone 下载源码，不要直接下载
