### ISSUE TITLE
链接不上数据库

### ISSUE THREAD

**Issue by hhy520wmf** [TangSengDaoDao/TangSengDaoDaoServer#51]
# 现象
ERROR 1045 (28000): Access denied for user 'root'@'ip' (using password: YES)
# 日志
![f9e7f43e540dbf4f21998e9e62b6f5b](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/3ecb58a3-abeb-4143-ada9-af769cbe282e)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/97502755/dee1eb2e-de94-4bdd-a8df-8524dc7a7774)

**Comment by tangtaoit** [comment]
看错误是密码不正确，看的配置 MYSQL_ROOT_PASSWORD密码设置的root，这个是不正确的文档上已经有说明mysql的密码有长度限制
