### ISSUE TITLE
唐僧叨叨和悟空IM的区别

### ISSUE THREAD

**Issue by kangsange** [TangSengDaoDao/TangSengDaoDaoServer#54]
# 现象
想请问一下作者，两者的区别是什么。
哪种场景用哪种会更好？
# 日志

**Comment by tangtaoit** [comment]
如果你的场景是想做一个类似微信的这种聊天软件，那么肯定用唐僧叨叨修改更快。如果你的场景是类似客服，直播弹幕，网站内通讯等用悟空IM合适。

悟空IM是没有UI界面的，只有服务端和对应的JSSDK，iOS SDK，Flutter SDk Android SDK等等，可以看成开源版本的网易云信或腾讯云信等这种服务

唐僧叨叨就类似一个产品级别的Demo

**Comment by kangsange** [comment]
悟空IM的JSSDK是否在唐僧叨叨里面适用？

**Comment by tangtaoit** [comment]
> 悟空IM的JSSDK是否在唐僧叨叨里面适用？

唐僧叨叨就是用的悟空IM的SDK
