### ISSUE TITLE
请问这个目录索引在哪里修改？

### ISSUE THREAD

**Issue by asecret** [TangSengDaoDao/TangSengDaoDaoServer#56]
这个能自定义么？
或者告诉我在那个文件上还得我直接文件修改一下。
![Uploading Screenshot_2023-12-05-11-19-32-67_bebc5b24fcfa09fec0f188d50da87968.jpg…]()

**Comment by asecret** [comment]
![Screenshot_2023-12-05-11-19-32-67_bebc5b24fcfa09fec0f188d50da87968](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7253009/14cc73f9-0b2b-41e0-8c73-05f6b598f482)
![Uploading Screenshot_2023-12-05-11-19-32-67_bebc5b24fcfa09fec0f188d50da87968.jpg…]()
![Uploading Screenshot_2023-12-05-11-19-32-67_bebc5b24fcfa09fec0f188d50da87968.jpg…]()

**Comment by tangtaoit** [comment]
这个是写在代码里的 需要修改服务端代码 搜关键字就能搜到

**Comment by asecret** [comment]
这个具体是那个文件？点开文件才能搜索吧。

**Comment by tangtaoit** [comment]
https://github.com/TangSengDaoDao/TangSengDaoDaoServer/blob/main/modules/robot/const.go
