### ISSUE TITLE
能在Windows上直接使用docker部署吗？

### ISSUE THREAD

**Issue by GaryWolf2023** [TangSengDaoDao/TangSengDaoDaoServer#59]
# 现象
我在Windows上使用docker部署后，部署成功，验证部署也通过。但是我在访问"唐僧叨叨后台管理"的时候总是出现502（新手开发）
# 日志

**Comment by tangtaoit** [comment]
看下浏览器的console日志，确定.env里你的IP配置正确了

**Comment by GaryWolf2023** [comment]
已经解决了，谢谢
