### ISSUE TITLE
web端运行后登录报404

### ISSUE THREAD

**Issue by zhangxilong123** [TangSengDaoDao/TangSengDaoDaoServer#6]
![a92cbebd79cbeace174e5dbd7575e14](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/52381336/6f4e6c06-d48f-4ecf-b55d-ff3f85f32897)

请求地址没有找到（404）

后台服务已经正常启动
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/52381336/97489d6f-ab0c-48e6-a3e5-84dcd122fbee)

**Comment by tangtaoit** [comment]
1. 如果你是源码运行的web参考此文档修改api地址： https://tangsengdaodao.com/dev/web/config.html

2. 如果是docker运行的增加环境变量 API_URL，API_URL格式为 http://xx.xx.xx.xx:8090/    xx.xx.xx.xx替换为你的ip
