### ISSUE TITLE
pc端如何切换自己搭建的服务ip

### ISSUE THREAD

**Issue by chengleig** [TangSengDaoDao/TangSengDaoDaoServer#60]
![screenshot-20231208-180806](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/5a6ea59e-f4d1-4202-9f23-d07a44e9132d)
我在自己的服务器上搭建了此服务，然后如何在pc端上修改ip，使其可以用自己的服务器ip去登录

**Comment by tangtaoit** [comment]
目前还不支持，需要自己下载源码修改地址后编译，后续会加上

**Comment by chengleig** [comment]
可以给下pc端源码地址和具体修改位置文件路径和修改内容嘛

**Comment by tangtaoit** [comment]
https://github.com/TangSengDaoDao/TangSengDaoDaoWeb

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/25480c4e-1ed9-4eaa-9425-2d4891c01bf3)
请问是修改哪个文件里面的地址

**Comment by tangtaoit** [comment]
https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/blob/main/apps/web/src/index.tsx#L11C4-L11C4 里的 apiURL

**Comment by chengleig** [comment]
好的谢谢

**Comment by chengleig** [comment]
比如现在的配置是const apiURL = "https://api.botgate.cn/v1/"   ，我把他换成const apiURL = "https://xx.xx.xx.xx:82/v1/",这样嘛

**Comment by tangtaoit** [comment]
http://xx.xx.xx.xx:8090/v1/ 如果你没配置https就是http

**Comment by chengleig** [comment]
![Uploading image.png…]()
修改ip重新打包后登录报错: 未知错误

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/b71b9188-50c7-4498-ab19-8e09712a3a1d)

**Comment by tangtaoit** [comment]
tauri的限制（应该也是系统的限制） 正式包 需要 api配置https，长连接需要配置wss

**Comment by chengleig** [comment]
我们使用的是自己服务器的地址测试用的，也不可以嘛

**Comment by tangtaoit** [comment]
只要打成可以分发的包 就需要https和wss，目前我们测试下来是这样的

**Comment by chengleig** [comment]
你好，我这边现在https和wss都调试好了，网页版的通信已经通了，但是尝试打包还是未知错误，const apiURL = "http://xxxxx.com:8090/v1/"，我是这么填的
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/33437ed4-e783-45c8-90d6-fd9e1606e9f0)

**Comment by tangtaoit** [comment]
> 你好，我这边现在https和wss都调试好了，网页版的通信已经通了，但是尝试打包还是未知错误，const apiURL = "[http://xxxxx.com:8090/v1/"，我是这么填的](http://xxxxx.com:8090/v1/%22%EF%BC%8C%E6%88%91%E6%98%AF%E8%BF%99%E4%B9%88%E5%A1%AB%E7%9A%84) ![image](https://private-user-images.githubusercontent.com/96517265/293151993-33437ed4-e783-45c8-90d6-fd9e1606e9f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDc2ODEsIm5iZiI6MTcwMzc0NzM4MSwicGF0aCI6Ii85NjUxNzI2NS8yOTMxNTE5OTMtMzM0MzdlZDQtZTc4My00NWM4LTkwZDYtZmQ5ZTE2MDZlOWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA3MDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTcwOGJjOGYxMjdlMjJlZjVhYmQ3NTFmMDYxOTM1NzI3MWY1OTQzYjZlODUwYmI1NjBiZGY4MDAzYWUwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TaiyKdzGrt0wyXrK9_0a5-khQFITquYzxzvQn1cHZ_0)

你还是填的http

**Comment by chengleig** [comment]
好了，但是发现一个问题。打包好的pc端
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/36fc119d-9e2f-4c31-acb8-c9a237479c29)
部分图片是损坏的，然后网页版使用https进去也是损坏的，通过http ip+端口是好的

**Comment by tangtaoit** [comment]
遇到问题第一时间提供错误信息，要不然我只能盲猜，我现在盲猜下，应该是你的文件服务没做https

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/37420110-c783-406b-bfb2-54da13aa5e25)
你猜的应该是对的，文件服务的https要如何做呢

**Comment by tangtaoit** [comment]
> ![image](https://private-user-images.githubusercontent.com/96517265/293304869-37420110-c783-406b-bfb2-54da13aa5e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjExNDksIm5iZiI6MTcwMzgyMDg0OSwicGF0aCI6Ii85NjUxNzI2NS8yOTMzMDQ4NjktMzc0MjAxMTAtYzc4My00MDZiLWJmYjItNTRkYTEzYWE1ZTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAzMzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGMxNTA4ZGFkZDhiMTJmMjg5MGI2YWUwYTNjY2YxMGVkNWE2ODUwMzdmYmFkZDdlYTRmZjM1YmQ2ZTQ5ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZfWOK0EcX_8LSfTt-TvO721NfNFxbvMzXefDiwwsVk) 你猜的应该是对的，文件服务的https要如何做呢

一样的 nginx里配置

**Comment by chengleig** [comment]
nginx如何配置呢，现在就是通过https访问不到9000
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/41275bea-5ef0-4bed-adb1-bdfedc80e75d)
![Uploading image.png…]()
http可以

**Comment by tangtaoit** [comment]
https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html 看minio的官网

**Comment by chengleig** [comment]
这个是针对minio的nginx配置，我这边的nginx配置的是针对唐僧叨叨的客户端
![Uploading image.png…]()

**Comment by chengleig** [comment]
我有个问题就是，https://tangsengdaodao.com/dev/backend/deploy-compose.html，我是根据这个目录快速部署的，但是前端这块要使用https域名，需要自己配置nginx，这一块配置咱们官方这边没有模板嘛。涉及到minio，wukongim，tsdd

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/79eb4d1f-7f2d-4dd8-9947-3e6e6bd89319)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/f3e281f4-5fc6-49e4-9319-b29d1754a00e)
还有一个问题就是，在群里添加好友，显示好友信息不存在，我感觉这个也是和nginx配置有关把

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/a4482677-8c94-4148-a558-49dafbc0669a)
这是根据docker-compose文档快速部署的

**Comment by tangtaoit** [comment]
> 我有个问题就是，[https://tangsengdaodao.com/dev/backend/deploy-compose.html，我是根据这个目录快速部署的，但是前端这块要使用https域名，需要自己配置nginx，这一块配置咱们官方这边没有模板嘛。涉及到minio，wukongim，tsdd](https://tangsengdaodao.com/dev/backend/deploy-compose.html%EF%BC%8C%E6%88%91%E6%98%AF%E6%A0%B9%E6%8D%AE%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%BD%95%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2%E7%9A%84%EF%BC%8C%E4%BD%86%E6%98%AF%E5%89%8D%E7%AB%AF%E8%BF%99%E5%9D%97%E8%A6%81%E4%BD%BF%E7%94%A8https%E5%9F%9F%E5%90%8D%EF%BC%8C%E9%9C%80%E8%A6%81%E8%87%AA%E5%B7%B1%E9%85%8D%E7%BD%AEnginx%EF%BC%8C%E8%BF%99%E4%B8%80%E5%9D%97%E9%85%8D%E7%BD%AE%E5%92%B1%E4%BB%AC%E5%AE%98%E6%96%B9%E8%BF%99%E8%BE%B9%E6%B2%A1%E6%9C%89%E6%A8%A1%E6%9D%BF%E5%98%9B%E3%80%82%E6%B6%89%E5%8F%8A%E5%88%B0minio%EF%BC%8Cwukongim%EF%BC%8Ctsdd)

你minio在nginx里配置转发后，然后把nginx转发的地址配置到tsdd.yaml里就可以了，至于nginx怎么转发minio看minio官方的配置


> https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

**Comment by chengleig** [comment]
tsdd.yaml是哪个文件，如何配置的呢

**Comment by tangtaoit** [comment]
> tsdd.yaml是哪个文件，如何配置的呢

如果你是docker部署的可以转换为环境变量

<img width="779" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/efe1300e-da3e-4690-a028-4effcfc2aa16">

完整配置参数： https://tsdaodao.com/dev/backend/fullconfig.html

minio节点

**Comment by chengleig** [comment]
是不是minio服务的9000端口必须要配置一个域名，并且开启https

**Comment by chengleig** [comment]
我在想的是，我用http访问唐僧叨叨，minio也是http，是可以访问的。我用https访问唐僧叨叨，minio也是https，就无法访问，我能直接写死minio的访问方式嘛，就是用http去访问

**Comment by tangtaoit** [comment]
> 是不是minio服务的9000端口必须要配置一个域名，并且开启https

是的，然后tsdd的minio配置里填写https的url
