### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by kangsange** [TangSengDaoDao/TangSengDaoDaoServer#66]
# 现象
按照宝塔安装的方式安装好了
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/37733022/be8c7332-6d28-495a-8179-8fb5f88657cf)

接口验证：正常，注册和登录都是OK的
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/37733022/2dc6ffab-8d48-49bd-9a2a-08fab86c8680)

但用jssdk就是连不上
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/37733022/c143de4c-34f3-49d2-ac9d-059628441ac1)

5001 5100 5200 5300 8306 82 83 端口可以确保都已经放开，

# 日志

**Comment by kangsange** [comment]
我猜测是wukongium的ip是不是没绑定，但是docker pull的代码在哪里修改wk配置文件呢

**Comment by kangsange** [comment]
wukongim的log


{"level":"debug","time":"2023-12-25 00:03:32","msg":"【UserAPI】req","req":{"uid":"admin","token":"b55b7194fe994bd7b61d861662295a6f","device_flag":0,"device_level":1}}
{"level":"debug","time":"2023-12-25 00:04:42","msg":"【Conn[[reactor-4]1]】max idle time exceeded, close the connection","maxIdle":2000,"lastActivity":2916,"conn":"Conn[1] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:04:42","msg":"【Dispatch】conn close for OnClose","conn":"Conn[1] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:04:42","msg":"【Processor】conn is close","conn":"Conn[1] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【ReactorSub-4】connection error","error":"handshake error: bad \"Connection\" header"}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Dispatch】conn close for OnClose","conn":"Conn[3] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Processor】conn is close","conn":"Conn[3] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【ReactorSub-4】connection error","error":"handshake error: bad \"Connection\" header"}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Dispatch】conn close for OnClose","conn":"Conn[4] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Processor】conn is close","conn":"Conn[4] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【ReactorSub-4】connection error","error":"handshake error: bad \"Connection\" header"}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Dispatch】conn close for OnClose","conn":"Conn[5] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Processor】conn is close","conn":"Conn[5] uid= fd={36} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【ReactorSub-1】connection error","error":"handshake error: bad \"Connection\" header"}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Dispatch】conn close for OnClose","conn":"Conn[2] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:06:10","msg":"【Processor】conn is close","conn":"Conn[2] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:07:22","msg":"【Conn[[reactor-1]6]】max idle time exceeded, close the connection","maxIdle":2000,"lastActivity":2946,"conn":"Conn[6] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:07:22","msg":"【Dispatch】conn close for OnClose","conn":"Conn[6] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:07:22","msg":"【Processor】conn is close","conn":"Conn[6] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:11:37","msg":"【Conn[[reactor-1]7]】max idle time exceeded, close the connection","maxIdle":2000,"lastActivity":2923,"conn":"Conn[7] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:11:37","msg":"【Dispatch】conn close for OnClose","conn":"Conn[7] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}
{"level":"debug","time":"2023-12-25 00:11:37","msg":"【Processor】conn is close","conn":"Conn[7] uid= fd={33} deviceFlag=APP deviceLevel=Slave deviceID="}

**Comment by kangsange** [comment]
上面log显示貌似没有用户名，但我本地打印一下是这样的
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/37733022/753be7bd-0e4f-4799-b9ef-4770947010b5)

显示uid和token是都有的，单独装一个wukongim的话，又是正常的

**Comment by kangsange** [comment]
82 /83 也出错
如下图：
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/37733022/b589eb20-cc04-4778-aeb5-1507486a38ec)


![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/37733022/4b158f7e-6184-4bc5-81c4-bbe0929966b2)

**Comment by tangtaoit** [comment]
> 82 /83 也出错 如下图： ![image](https://private-user-images.githubusercontent.com/37733022/292680718-b589eb20-cc04-4778-aeb5-1507486a38ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0ODc4OTgsIm5iZiI6MTcwMzQ4NzU5OCwicGF0aCI6Ii8zNzczMzAyMi8yOTI2ODA3MTgtYjU4OWViMjAtY2MwNC00Nzc4LWFlYjUtMTUwNzQ4NmEzOGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA2NTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZmI5NjI2NzBhN2JmNGE3MWMxYjVmNjI4Zjg3ZmNiODQyOGQwMWMxMDEzYmNkYzkyY2VhM2M3YzU4ZGE3OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yy2cRR1puHUXC4OKJio08u4fEZr0WEhSZXYIRykCMnE)
> 
> ![image](https://private-user-images.githubusercontent.com/37733022/292680729-4b158f7e-6184-4bc5-81c4-bbe0929966b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0ODc4OTgsIm5iZiI6MTcwMzQ4NzU5OCwicGF0aCI6Ii8zNzczMzAyMi8yOTI2ODA3MjktNGIxNThmN2UtNjE4NC00YmM1LTgxYzQtYmJlMDkyOTk2NmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA2NTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZDRjNDhjZTlmYmQzMDBjNzA0MzY2YjRkYTJlYzEzMjliOGM0ZGE0MjFhNGFjMTQ0NTAwYjkzM2MxOGIwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpi4BuqAer8YozVE8rSHM_9XopRt2MU_rhkPLX-eVOg)

api端口是 8090
