### ISSUE TITLE
 tsdd_minio_1容器unhealthy

### ISSUE THREAD

**Issue by chengleig** [TangSengDaoDao/TangSengDaoDaoServer#67]
# 现象
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/bc0a2ec8-9c67-4457-9229-0d8d50cc4a28)

# 日志

**Comment by tangtaoit** [comment]
<img width="579" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/4929dd2a-2d34-47b9-acc4-5c0b576aecec">

healthcheck 配置了吗？

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/56d9d5bd-d2f9-4d8d-9e64-834a541a1000)
我是复制的官网的配置

**Comment by chengleig** [comment]
重启容器包括直接docker-compose down up 我都试过，还是unhealthy

**Comment by tangtaoit** [comment]
镜像使用  minio/minio:RELEASE.2023-07-18T17-49-40Z 看看

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/d68f262c-ca77-4407-9ed3-5420e4f41613)
容器就绪了，但是看日志好像有点不对

**Comment by tangtaoit** [comment]
是不是你设置的MINIO_ROOT_USER或MINIO_ROOT_PASSWORD太短了？

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/4a43d589-1096-49ae-b9b8-5ff9dffffae7)
use是默认的，密码这样的形式可以嘛
