### ISSUE TITLE
请问我需要配置域名而且是https访问唐僧叨叨，nginx需要如何配置，我配置了一个，可以登录进去，但是好像功能无法使用

### ISSUE THREAD

**Issue by chengleig** [TangSengDaoDao/TangSengDaoDaoServer#68]
# 现象
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/bdaa89c2-e133-4b08-9e08-e047c7967c34)

# 日志

**Comment by tangtaoit** [comment]
那个地方无法使用，具体错误是什么？我们需要更详细点的数据。

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/dbea6f0f-3360-4cb9-8518-07823dd7a67d)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/959e24c7-d912-4330-885a-86231e7ff07c)
第一个是我用域名的，第二个是我用Ip+端口的

**Comment by tangtaoit** [comment]
浏览器的console日志截图看下

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/34b19eb6-5976-45d1-9810-882ea1353d6e)
websock我nginx也配置了，是要加个路由到5200嘛，要怎么加呢
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/3737731a-bd83-47b9-abce-dd807900245a)

**Comment by tangtaoit** [comment]
这错误显示的是 你网站使用的https 但是你的websocket不是wss的，你要配置下wss，chrome好像https的网站 必需配置wss的websocket

**Comment by chengleig** [comment]
请问长连接到5200的nginx前缀是什么呢

**Comment by tangtaoit** [comment]
> 请问长连接到5200的nginx前缀是什么呢

前缀？还是后缀？ 没有后缀

**Comment by chengleig** [comment]
如何我要配置长连接到5200端口，location后面不是要跟前缀嘛，或者有没有nginx模板，私有化部署的话，除了自己搭建一个nginx转发，还有其他方法嘛

**Comment by tangtaoit** [comment]
> 如何我要配置长连接到5200端口，location后面不是要跟前缀嘛，或者有没有nginx模板，私有化部署的话，除了自己搭建一个nginx转发，还有其他方法嘛

你location跟前缀 这个你可以自己随便写个。你只需要在对外的wsAddr里也加上你的前缀即可

```
external:
   wsAddr: ""
```

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/493218c5-aaf7-41d9-ad40-e0128f11a9c5)
我加了到5200端口的长连接，自定义了前缀，但是还是不行。 
还有
external:
   wsAddr: ""是写在哪里的

**Comment by tangtaoit** [comment]
> ![image](https://private-user-images.githubusercontent.com/96517265/293120967-493218c5-aaf7-41d9-ad40-e0128f11a9c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzExNzQsIm5iZiI6MTcwMzczMDg3NCwicGF0aCI6Ii85NjUxNzI2NS8yOTMxMjA5NjctNDkzMjE4YzUtYWFmNy00MWQ5LWFkNDAtZTAxMjhmMTFhOWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAyMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDQyOGM1YzhmY2UzZDUzYzY0ZmY3NmY0YjNjZmVjNDQ4MzY4NWY2YmY4MmYwMDU1OGViYmM0Y2MzMjM4NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G-zc_X_dfGp7cKHqeLNHK5fnKTO8iSPUCs1UAp1ThFo) 我加了到5200端口的长连接，自定义了前缀，但是还是不行。 还有 external: wsAddr: ""是写在哪里的

wk.yaml里，看文档

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/c56f1de8-6071-4198-aa34-d2de86adefe5)
打开这里重启了容器，还是不行诶

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/25020500-6ae8-4fda-b5ab-a5396cbf5d66)
接口工具调不通

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/51c464cc-034d-4411-bfba-2762def9a9ee)
加上wss以后，显示一直重连

**Comment by chengleig** [comment]
是不是5200服务端有问题，调不通

**Comment by tangtaoit** [comment]
```
external:
    ip:
```

这个IP配置下，对外的IP，然后检查下端口是否都开放

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/b6ee95b7-0f79-4d2b-bc74-eaa4090b49a2)
我是使用docker-compose的。ip读取的变量
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/00e12b3d-9ce8-4f0d-97c0-afa7f73aba28)

![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/95a8ea1a-9166-46fd-8741-e5580b523f9a)

![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/15bfc668-d2aa-4831-be26-1d09abb5500d)
端口和安全组都是开的

**Comment by tangtaoit** [comment]
<img width="477" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/248a29a9-c687-4af3-8e5f-e6f51fee35cd">

这里应该配置你nginx的地址

**Comment by chengleig** [comment]
是的，这里配置的是nginx地址

**Comment by tangtaoit** [comment]
> 是的，这里配置的是nginx地址

你截图的明显不是 
<img width="489" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/5ae83910-c059-4b5d-98a0-dc4e09b3fe38">

**Comment by chengleig** [comment]
你的意思是wss改成http是吧，我的意思是里面的ip是nginx地址，这个是改成http还是https呢

**Comment by tangtaoit** [comment]
> 你的意思是wss改成http是吧，我的意思是里面的ip是nginx地址，这个是改成http还是https呢

你nginx不是有/websocket前缀吗？ WK_EXTERNAL_WSSADDR= wss://你的域名/websocket

**Comment by chengleig** [comment]
可以了，感谢支持！

**Comment by chengleig** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/268e05f2-7431-48d7-ab1d-dff31e3c15a9)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/d361e790-0490-4cf8-8065-f00713d4d9a4)
请问这个在群里加好友，报好友信息不存在，是缺哪里的配置嘛

**Comment by tangtaoit** [comment]
> ![image](https://private-user-images.githubusercontent.com/96517265/293316700-268e05f2-7431-48d7-ab1d-dff31e3c15a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzA4OTcsIm5iZiI6MTcwMzgzMDU5NywicGF0aCI6Ii85NjUxNzI2NS8yOTMzMTY3MDAtMjY4ZTA1ZjItNzQzMS00OGQ3LWFiMWQtZGZmMzFlM2MxNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA2MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjODM5ODcyNDM4MThhZjIyZWM1Y2ViNDU4YWJlZTlhY2UyNjdmZGU0MzFhYmZiZjIwNDgyYzA2ZWY0ZTRiYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2zQfhcPnWV0r-kHw9pBKnPs0lkLHr4-EtQHSdnPzGLs) ![image](https://private-user-images.githubusercontent.com/96517265/293316736-d361e790-0490-4cf8-8065-f00713d4d9a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzA4OTcsIm5iZiI6MTcwMzgzMDU5NywicGF0aCI6Ii85NjUxNzI2NS8yOTMzMTY3MzYtZDM2MWU3OTAtMDQ5MC00Y2Y4LTgwNjUtZjAwNzEzZDRkOWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA2MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYjg3YzlkOGQ2ODVmOTM0NmVmMWEzNmI0ZjlmZmM5NDhkNGZhMTgzZTQ1ZTcxNGM5MDgxZjE0NjgyZDU3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sm3X1tAn7AOhslp6zA-fRndnGYUI-LB5FmwLLEHp7WM) 请问这个在群里加好友，报好友信息不存在，是缺哪里的配置嘛

这时另外一个问题 你开个新的issue
