### ISSUE TITLE
群聊里面添加好友

### ISSUE THREAD

**Issue by chengleig** [TangSengDaoDao/TangSengDaoDaoServer#69]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/1b57bb9a-5081-48e5-86bb-c98ebfa1e328)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/a5854d23-ed58-4a26-bdbd-17187bc62808)

请问这个在群里加好友，报好友信息不存在，是缺哪里的配置嘛

**Comment by tangtaoit** [comment]
也许是个BUG，我们先确认下

**Comment by chengleig** [comment]
好的

**Comment by chengleig** [comment]
怎么样啦，可以修复嘛

**Comment by No8blackball** [comment]
> 怎么样啦，可以修复嘛

确定下被申请的人是如何加入群聊的。二维码还是用户邀请加入。申请加入的接口参数`vercode `字段有值嘛

**Comment by chengleig** [comment]
二维码

**Comment by chengleig** [comment]
申请加入的接口参数vercode 字段如何查询到呢

**Comment by chengleig** [comment]
代码层面我没动过，直接跑的官网的开源代码，解析的二维码地址是http://xx.xx.xx.xx
:8090/v1/qrcode/ddc60d9c70684fcb922cb377fa1e444a

**Comment by No8blackball** [comment]
> 代码层面我没动过，直接跑的官网的开源代码，解析的二维码地址是http://xx.xx.xx.xx :8090/v1/qrcode/ddc60d9c70684fcb922cb377fa1e444a

扫码进入的群成员未生成验证码，拉最新的代码试试

**Comment by chengleig** [comment]
我是通过docker-compose部署的，可以直接给我一个最新的镜像号嘛。https://tangsengdaodao.com/dev/backend/deploy-compose.html，这个是我的部署文档

**Comment by No8blackball** [comment]
> 。申请加入的接口

registry.cn-shanghai.aliyuncs.com/wukongim/tangsengdaodaoserver:latest

**Comment by chengleig** [comment]
使用了最新的镜像，还是一样的问题

**Comment by chengleig** [comment]
或者我可以如何给你提供错误信息

**Comment by No8blackball** [comment]
> 使用了最新的镜像，还是一样的问题

通过二维码加入群的老成员是没有加好友验证码了。试下新成员通过二维码进群，然后申请加这个成员为好友看还有错误嘛

**Comment by chengleig** [comment]
新加入的成员可以添加好友了，感谢
