### ISSUE TITLE
群二维码失效时间过快，标注的是持续一个星期，大概一天就会失效

### ISSUE THREAD

**Issue by chengleig** [TangSengDaoDao/TangSengDaoDaoServer#70]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/b69c95a1-35d8-473a-973d-3622652725c0)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/96517265/0f799fd5-ca12-4707-bc8e-079d5816650f)

**Comment by No8blackball** [comment]
官方的demo未发现这个问题哦

**Comment by chengleig** [comment]
https://tangsengdaodao.com/dev/backend/deploy-compose.html
我是通过docker-compose私有化部署的

**Comment by tangtaoit** [comment]
更新到最新版本

**Comment by chengleig** [comment]
哪个镜像更新到latest

**Comment by tangtaoit** [comment]
> 哪个镜像更新到latest

registry.cn-shanghai.aliyuncs.com/wukongim/tangsengdaodaoserver:latest
