### ISSUE TITLE
现有功能有没有类似可以用拦截器加日志的能力？试了一下自己加但是不生效，请教一下原因，感谢。

### ISSUE THREAD

**Issue by AKIRAGuo** [TangSengDaoDao/TangSengDaoDaoServer#76]
# 现象
添加拦截器但是接口访问不受拦截器影响。

# 日志
添加代码如下
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7629219/79c5564b-2023-4334-beae-06c334b2c5e5)
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/7629219/499a11d2-2f32-4a2b-8247-afe0eb848db1)

**Comment by tangtaoit** [comment]
你这是给GRPC添加拦截器吗？ 你是要实现什么功能？我理解的应该也不需要给GRPC添加拦截器，你可以在webhook回调里直接处理你的业务即可。

**Comment by AKIRAGuo** [comment]
> 你这是给GRPC添加拦截器吗？ 你是要实现什么功能？我理解的应该也不需要给GRPC添加拦截器，你可以在webhook回调里直接处理你的业务即可。

你好 我想要实现在拦截器这边加一个接口拦截，做一个记录操作日志的功能，如果能抓到接口在webhook处处理也可以，请问具体在哪个方法可以拦截到接口呢？

**Comment by AKIRAGuo** [comment]
> 你这是给GRPC添加拦截器吗？ 你是要实现什么功能？我理解的应该也不需要给GRPC添加拦截器，你可以在webhook回调里直接处理你的业务即可。

这块webhook是不是不是全局接口拉起的地方 感觉好像是做消息一类拉取的地方，有没有全局可以拦截接口的地方？

**Comment by tangtaoit** [comment]
https://github.com/TangSengDaoDao/TangSengDaoDaoServer/blob/main/modules/webhook/api.go#L136 所有的webhook事件都会经过SendWebhook方法 在这个方法里加上你的逻辑就行（如果你的逻辑很耗时，建议做成异步，要不然会阻塞其他事件）
