### ISSUE TITLE
客户端连接mysql问题(compose部署)

### ISSUE THREAD

**Issue by jimbung** [TangSengDaoDao/TangSengDaoDaoServer#79]
采用compose部署后，如何通过客户端连接mysql?

**Comment by tangtaoit** [comment]
参考文档： 
https://tsdaodao.com/dev/backend/deploy-mysql.html

如果不使用自带的连接mysql的管理工具：

服务器：应该为可访问到的mysql的IP
用户名： root
密码：部署的时候配置的mysql密码（.env里的MYSQL_ROOT_PASSWORD值）

**Comment by jimbung** [comment]
已解决，谢谢！
