### ISSUE TITLE
客户端拉黑功能不好用

### ISSUE THREAD

**Issue by ruiwen996** [TangSengDaoDao/TangSengDaoDaoServer#80]
# 现象
用户之间私聊，拉黑之后拉不出来，还是被禁言状态
# 日志

**Comment by tangtaoit** [comment]
docker-compose.yaml里 

tangsengdaodaoserver的镜像换成 registry.cn-shanghai.aliyuncs.com/wukongim/tangsengdaodaoserver:v1.5

wukongim的镜像换成 registry.cn-shanghai.aliyuncs.com/wukongim/wukongim:v1.2

前端需要重新拉出黑名单 再拉入黑名单即可生效
