### ISSUE TITLE
/api/v1/manager/login(502 Bad Gateway)

### ISSUE THREAD

**Issue by leobc1128** [TangSengDaoDao/TangSengDaoDaoServer#82]
# 现象
后台管理界面能打开，但是无法登陆，提示/api/v1/manager/login(502 Bad Gateway)
# 日志
/api/v1/manager/login(502 Bad Gateway)
axios-a82b6be5.js

**Comment by tangtaoit** [comment]
502应该是访问不到api，确定这个环境变量设置准确了？

<img width="555" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/499f0e4b-1a89-425c-9ea5-335dded32aef">

**Comment by leobc1128** [comment]
<img width="626" alt="1709709650678" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/89430860/04e20b39-cf7f-439d-8ee8-79f6eefbd47b">
目前设置的变量是本地的

**Comment by tangtaoit** [comment]
127肯定不行 要局域网IP
