### ISSUE TITLE
web端消息撤回失败

### ISSUE THREAD

**Issue by asuydzl** [TangSengDaoDao/TangSengDaoDaoServer#85]
使用源码部署到本地后，web端撤回消息显示失败。调试发现是由于musql中未存储该消息，这是什么原因呢？
同样的由于未能存储该消息，已读未读也上传失败。

![errrrlog](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/165118680/c6457f63-7ef2-404f-8bad-e3aaf224fff4)

**Comment by tangtaoit** [comment]
<img width="748" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/84451d01-216e-485b-95b9-bba7d46ff44c">

WuKongIM的 WK_WEBHOOK_GRPCADDR 配置的tangsengdaodaoserver:6979 地址改成能访问到你本地的ip:6979的地址

**Comment by asuydzl** [comment]
> <img alt="image" width="748" src="https://private-user-images.githubusercontent.com/3895878/317117435-84451d01-216e-485b-95b9-bba7d46ff44c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTU4NDEsIm5iZiI6MTcxMTUxNTU0MSwicGF0aCI6Ii8zODk1ODc4LzMxNzExNzQzNS04NDQ1MWQwMS0yMTZlLTQ4NWItOTViOS1iYmE3ZDQ2ZmY0NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDQ1OTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGEyZWRhYTliZDk5NDZkYzlhNWRkM2Q3ZjQ1MmFiZjQxMTlkNDNkYjQ5NjliZWIzYTI2MGJjZjVhZjQ1NjRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vWy1U18U60IGueC82ID5DZnp6u-RaMPPyQQIsQUdW2g">
> WuKongIM的 WK_WEBHOOK_GRPCADDR 配置的tangsengdaodaoserver:6979 地址改成能访问到你本地的ip:6979的地址
好嘞，谢谢大神
