### ISSUE TITLE
根据用户请求api携带的token，找到用户

### ISSUE THREAD

**Issue by WakeOneT** [TangSengDaoDao/TangSengDaoDaoServer#86]
# 现象

根据用户请求api携带的token，找到用户

找到用户在系统的uid 

# 日志

**Comment by tangtaoit** [comment]
啥意思？

**Comment by WakeOneT** [comment]
![CleanShot 2024-04-03 at 16 05 44@2x](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/124677933/3fa289ab-8f8b-4a17-b58a-cd49ea975b28)
用户携带token访问api , 对一些请求我想调试识别，是那些uid的用户发送的。

数据库没有存储token我不知道怎么找到这个token属于哪个用户，或者识别到他的7位id

**Comment by WakeOneT** [comment]
> <img alt="image" width="490" src="https://private-user-images.githubusercontent.com/3895878/319123203-96c376ca-b09c-4164-b708-0479fd157a43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDExODEsIm5iZiI6MTcxMjE0MDg4MSwicGF0aCI6Ii8zODk1ODc4LzMxOTEyMzIwMy05NmMzNzZjYS1iMDljLTQxNjQtYjcwOC0wNDc5ZmQxNTdhNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTA0MTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY4Njg3N2QyMzJkMWRlNWI4NzM3ODc0MjUwNGU3ODJkOGU2NzEzYmNlZDdmMTFmYzhjYmU0NWY4YTdiMzNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dNXDFsmxnDxzs_CwDK6BV4fPqqxh3Uo0m5dXN3HVHjA">
> 通过 `loginUID := c.GetLoginUID()` 就能获取到当前token的用户

需要的方法是，token反获取uid， 用用户账号密码能获得token 这个可以模拟登录一下就拿到了

**Comment by tangtaoit** [comment]
用户token与uid的关系是存在redis里的，具体怎么个获取逻辑 参考`c.GetLoginUID()` 方法里的方式
