### ISSUE TITLE
我是go新手小白。请问我要如何在tsdd.yaml新增自己的配置并使用？

### ISSUE THREAD

**Issue by xwg-github** [TangSengDaoDao/TangSengDaoDaoServer#87]
# 现象 
我是在main.go这样新增了
	// 初始化context
	ctx := config.NewContext(cfg)
	ctx.Event = event.New(ctx)
	// 新增配置
	ctx.SetValue(vp.GetString("other"), "other")
项目中使用是这样：
        u.ctx.Value("other")
觉得这样不太方便
# 日志

**Comment by tangtaoit** [comment]
看这里 https://github.com/TangSengDaoDao/TangSengDaoDaoServerLib/blob/main/config/config.go

会转换成一个config对象.

**Comment by xwg-github** [comment]
嗯。这里我知道，config是TangSengDaoDaoServerLib库的，我想要新增一个其他字段

**Comment by tangtaoit** [comment]
> 嗯。这里我知道，config是`TangSengDaoDaoServerLib`库的，我想要新增一个其他字段

在`TangSengDaoDaoServerLib`的config里加一个属性即可，参考其他的配置。

`go.mod`里可以通过 replace的方式引入本地`TangSengDaoDaoServerLib`这样改就方便

**Comment by xwg-github** [comment]
这样做就得引入到本地了。我想保留远程依赖的同时，新增自己的配置。

**Comment by tangtaoit** [comment]
> 这样做就得引入到本地了。我想保留远程依赖的同时，新增自己的配置。

新增配置必须改`TangSengDaoDaoServerLib`库 否则只能通过u.ctx.Value("other")方式获取

**Comment by tangtaoit** [comment]
还有一种办法就是，你业务层也创建一个配置对象，初始化的时候类似 `TangSengDaoDaoServerLib`一样 将vp里的配置映射到你业务层的配置对象上，这样其他地方调用你业务层的配置对象即可

**Comment by xwg-github** [comment]
好的，谢谢
