### ISSUE TITLE
部署后，文字聊天正常，聊天发送图片失败

### ISSUE THREAD

**Issue by yagerhw** [TangSengDaoDao/TangSengDaoDaoServer#88]
# 现象
聊天中发送图片失败

# 日志
tangsengdaodaoserver-1   | [GIN] 2024/04/27 - 16:31:25 | 200 |    4.383125ms |    192.168.65.1 | GET      "/v1/file/upload?type=chat&path=/1/6db485eee64a47b39846fe6a35c23682/1714206967652.png"
tangsengdaodaoserver-1   | {"level":"error","time":"2024-04-27 16:31:55","msg":"【File】检测 chat目录是否存在错误"}
tangsengdaodaoserver-1   | {"level":"error","time":"2024-04-27 16:31:55","msg":"【File】上传文件失败！","error":"Get \"http://192.168.2.219:9000/chat/?location=\": dial tcp 192.168.2.219:9000: i/o timeout"}
tangsengdaodaoserver-1   | [GIN] 2024/04/27 - 16:31:55 | 400 | 30.298603139s |    192.168.65.1 | POST     "/v1/file/upload?type=chat&path=/1/6db485eee64a47b39846fe6a35c23682/1714206967652.png"

**Comment by tangtaoit** [comment]
192.168.2.219:9000: i/o timeout， 检查下tangsengdaodaoserver服务里能否访问到 192.168.2.219:9000
