### ISSUE TITLE
api接口没问题 长链接不行

### ISSUE THREAD

**Issue by CarryYang2020** [TangSengDaoDao/TangSengDaoDaoServer#89]
# 现象
我有台服务器 一台地址为192.168.10.15 一台为192.168.10.151 在151的机器上用docker部署好了唐僧叨叨，.env设置的ip地址也是设置的192.168.10.151,下载好手机app后在局域网中可以正常登录发消息。现在我在192.168.10.15上做了公网映射 域名为xxx.xxxx.com，用app可以外网登录 登录后显示链接断开，经网页调试一直卡在ws://192.168.10.151,但应该是要访问xxx.xxxx.com这个域名才能访问到内网的192.168.10.151，请问我应该如何设置？

# 日志

**Comment by tangtaoit** [comment]
WuKongIM的对外服务的配置要换成你的域名

<img width="828" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/3895878/76d21aee-92c4-4efd-b418-fc1bca9583e6">

配置说明：https://githubim.com/guide/fullconfig.html
