### ISSUE TITLE
登录成功后显示已断开什么情况

### ISSUE THREAD

**Issue by leige6** [TangSengDaoDao/TangSengDaoDaoServer#9]
# 现象
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/20181291/af6dfdd5-7f79-479a-93a8-6a4d6f6324fc)

# 日志
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/20181291/da6d7534-c7bf-4850-af0d-3a7e53e4fbe4)

**Comment by tangtaoit** [comment]
能登录成功，说明API没问题，连接不了，需要查看下/v1/users/xxx/im 这个接口返回的wsAddr的地址是否正确。

图上看到的是返回的(ws://172.18.0.3:5200)内网地址，那肯定连接不上

解决方式：

检查下tsdd.yaml的如下配置

```
external:
  ip: "" #  改为服务器的IP地址
```

ip为服务器对外可访问的IP地址，不需要加端口
