### ISSUE TITLE
本地部署项目，配置文件个别变量不生效

### ISSUE THREAD

**Issue by anthony-china** [TangSengDaoDao/TangSengDaoDaoServer#90]
# 现象
本地部署项目，配置文件个别变量不生效
# 日志
比如说用户在线的配置

**Comment by tangtaoit** [comment]
是docker compose部署的吗？ 按照最新的官网教程，配置可以按照配置文档里的配置 转换成大写的 然后配置在.env文件里

**Comment by anthony-china** [comment]
> 是docker compose部署的吗？ 按照最新的官网教程，配置可以按照配置文档里的配置 转换成大写的 然后配置在.env文件里

不是docker部署，我是本地部署的，但是有些配置文件的功能就是不生效。

**Comment by anthony-china** [comment]
> 是docker compose部署的吗？ 按照最新的官网教程，配置可以按照配置文档里的配置 转换成大写的 然后配置在.env文件里

本地部署有啥办法解决配置文件不生效问题吗。

**Comment by tangtaoit** [comment]
通过 --config 可以指定配置路径
