### ISSUE TITLE
消息引用回复问题

### ISSUE THREAD

**Issue by chinahcp888** [TangSengDaoDao/TangSengDaoDaoServer#91]
# 现象
在引用自己发出去的消息时，自己又主动撤回了被引用的那条消息，引用消息上的消息没有被撤回

https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/164016488/8d5aad3b-1f4a-4d55-a531-42e002104b3c

**Comment by chinahcp888** [comment]
我发那个视频是接收方的，发送发的没问题， 我就没发出视频，只有在群聊中发现了这个问题

**Comment by No8blackball** [comment]
> 我发那个视频是接收方的，发送发的没问题， 我就没发出视频，只有在群聊中发现了这个问题

收到刷新消息时，如果消息标记撤回时也要把回复消息撤回
https://github.com/TangSengDaoDao/TangSengDaoDaoAndroid/blob/master/wkuikit/src/main/java/com/chat/uikit/chat/ChatActivity.java
中的监听刷新消息方法中最后有处理

**Comment by chinahcp888** [comment]
我没有看到哪里有这个操作，完全替换了你的方法，依旧存在这个问题

**Comment by chinahcp888** [comment]
我运行了你们的代码，这个问题并没有解决啊，你监听处理之对其他人的消息起作用，引用自己发出去的图片消息，再撤回图片，被引用的消息上图片还在，你试试

**Comment by No8blackball** [comment]
我用我们官方的demo撤回被回复的图片，回复消息也会显示撤回。你打印看看你那边不能撤回的回复消息的messageid和实际的消息messageID是否一致。如果不一致才会出现这种情况，如果一致就是UI上刷新问题

**Comment by No8blackball** [comment]
> 我运行了你们的代码，这个问题并没有解决啊，你监听处理之对其他人的消息起作用，引用自己发出去的图片消息，再撤回图片，被引用的消息上图片还在，你试试

这个撤回问题应该是消息对象内容未改变调用刷新导致无效了，更新下最新的demo测试下
