### ISSUE TITLE
更新邀请注册后，管理端新增用户和群报错

### ISSUE THREAD

**Issue by asuydzl** [TangSengDaoDao/TangSengDaoDaoServer#92]
# 现象
管理端新增用户或者群后，在处理用户注册事件时，因为无法获取邀请者uid和邀请码报错
![屏幕截图 2024-06-25 083745](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/165118680/d41bf72c-8e3c-4914-b96e-71f2e871ae37)

# 日志
2024/06/25 08:34:27 [Recovery] 2024/06/25 - 08:34:27 panic recovered:
interface conversion: interface {} is nil, not string

**Comment by asuydzl** [comment]
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/165118680/1e5e6076-62a3-4b18-a3a5-dee1053b12af)
无法获取邀请者uid 和邀请码
![image](https://github.com/TangSengDaoDao/TangSengDaoDaoServer/assets/165118680/076d3522-6664-4312-82a0-06e0b8758f9e)

**Comment by No8blackball** [comment]
开源版本没有邀请码模块
