### ISSUE TITLE
关于群解散的功能疑惑

### ISSUE THREAD

**Issue by koxiong** [TangSengDaoDao/TangSengDaoDaoServer#95]
在最新一个版本中，我注意到增加了群解散的功能：groups.DELETE("/:group_no/disband", g.disband) ，相关的代码处理中，在群解散完成后，会向群组成员发送TIP消息：
```
content := "{0}已解散该群聊"
	err = g.ctx.SendMessage(&config.MsgSendReq{
		Header: config.MsgHeader{
			NoPersist: 0,
			RedDot:    1,
			SyncOnce:  0, // 只同步一次
		},
		ChannelID:   req.GroupNo,
		ChannelType: common.ChannelTypeGroup.Uint8(),
		Payload: []byte(util.ToJson(map[string]interface{}{
			"from_uid":  req.Operator,
			"from_name": req.OperatorName,
			"content":   content,
			"extra": []config.UserBaseVo{
				{
					UID:  req.Operator,
					Name: req.OperatorName,
				},
			},
			"type": common.Tip,
		})),
	})
```
我的问题是，看上去这就是一条普通的TIP消息，那么接收的客户端如何知道这是一个群解散的消息，以便及时的关闭群的输入功能呢。
另外，是不是Android 的app还没有加入群解散的相关功能。
感谢大佬的解答。谢谢！

**Comment by tangtaoit** [comment]
调用了WuKongIM的接口，WuKongIM层在通讯层就将此群解散了，所以所有人消息是发不除去的，通过WuKongIM返回的reasonCode就能知道原因。（当然如果UI需要一些变化的话，唐僧叨叨可以向客户端再发个消息。）

**Comment by koxiong** [comment]
> 调用了WuKongIM的接口，WuKongIM层在通讯层就将此群解散了，所以所有人消息是发不除去的，通过WuKongIM返回的reasonCode就能知道原因。（当然如果UI需要一些变化的话，唐僧叨叨可以向客户端再发个消息。）

感谢您的解答，是不是可以在这个TIP消息的Payload字段，增加一个自定义字段，用于指示TIP的类型，便于客户端处理，也节省了唐僧叨叨再发消息的开销。我想问的是，规范上是否支持payload的自定义字段

**Comment by tangtaoit** [comment]
> > 调用了WuKongIM的接口，WuKongIM层在通讯层就将此群解散了，所以所有人消息是发不除去的，通过WuKongIM返回的reasonCode就能知道原因。（当然如果UI需要一些变化的话，唐僧叨叨可以向客户端再发个消息。）
> 
> 感谢您的解答，是不是可以在这个TIP消息的Payload字段，增加一个自定义字段，用于指示TIP的类型，便于客户端处理，也节省了唐僧叨叨再发消息的开销。我想问的是，规范上是否支持payload的自定义字段

可以的
